---
title: "R in 3 Months: Fall 2022"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

# Welcome to R in 3 Months!

Thanks for joining us for the 4th edition of R in 3 Months.

We're really excited to have you on the course and to see what you end up building with R.

Below is a work-in-progress schedule for our time together. Lessons will be added to the [R in 3 Months (Fall 2022) course on the R for the Rest of Us website](https://rfortherestofus.com/courses/r-in-3-months-fall-2022/).

Here are some links you'll use throughout our time together:

-   A list of all participants can be found [here](https://docs.google.com/spreadsheets/d/1lD5SgbdG24HfV4Glo80u7j7I3o-XpRJESYcQ50eXbEc "Opens in a new window").

-   We're using a [GitHub repository for R in 3 Months Fall 2022 Cohort](https://github.com/rfortherestofus/rin3-fall-2022 "Opens in a new window") (you're here right now!). 

-   Live sessions will happen Thursdays at 10am Pacific time. [You can join the Zoom call with this link](https://us02web.zoom.us/j/81827757156?pwd=SWZOMmVaUTYwUGFNTGFQSnAyQ05xUT09 "Opens in a new window").

-   Charlie will hold office hours Tuesdays at 12pm Pacific time. [You can join with this link](https://us02web.zoom.us/j/83230184104?pwd=RGkweWNMNy9zK3NvUVVPeGNQQWp5dz09 "Opens in a new window").

<hr>

# Weekly Agenda

### Week 01 (2022/09/22): Welcome

| Videos to watch            | Project Assignment                                                                                                 | Live Session                                                                      |
|:---------------------------|:-------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------|
| Complete "Getting Started" | \- Create an RStudio Project <br> - Create an RMarkdown document <br> - Use GitHub Gists to submit your assignment | \- Introductions and getting to know one another <br> - Getting started questions |

<hr>

### Week 02 (2022/09/29): RMarkdown

| Videos to watch                           | Project Assignment                                                                 | Live Session                                                                                                                                                                                           |
|:------------------------------------------|:-----------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Complete "Fundamentals RMarkdown lessons" | \- Analyse your dataset in your .Rmd report <br> - Add your data file to your Gist | \- Common issues from last week's assignment <br> - Choosing datasets <br> - Using {wakefield} to create fake datasets <br> **Group Work** <br> - Sharing projects <br> - Debugging a broken .Rmd file |

<hr>

### Week 03 (2022/10/06): Data wrangling and analysis

| Videos to watch                                | Project Assignment                             | Live Session                                                                                                                                               |
|:-----------------------------------------------|:-----------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------|
| Complete "Fundamentals data wrangling lessons" | \- Create a data visualisation of your dataset | \- Four tips from last week's assignment <br> - Code chunk behaviour <br> - Typos happen to everyone <br> - Workflow advice <br> **Group Work** <br> - ??? |

<hr>

### Week 04 (2022/10/13): Data viz

| Videos to watch                          | Project Assignment                                                           | Live Session                                                                                                  |
|:-----------------------------------------|:-----------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------|
| Complete "Fundamentals data viz lessons" | \- **No new assignment** <br> - Book a 1:1 with Charlie to discuss your work | \- Four tips from last week's assignment <br> - Work flow advice <br> - Dataviz examples from David & Charlie |

### Week 05 (2022/10/20): Catch-up week!

> There's not a live session this week. Charlie's office hours will go ahead and you're invited to book a 1:1 to discuss your project.

### Week 06 (2022/10/27): Git & GitHub

| Videos to watch         | Project Assignment                                                                                 | Live Session                                                                                         |
|:------------------------|:---------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------|
| Complete "Git + GitHub" | \- Figure out ways that your data is **not** tidy <br> - Use the {tidyr} package to tidy your data | \- Four tips from last week's assignment <br> - Intro to Git & GitHub <br> **Group Work** <br> - ??? |

<hr>

### Week 07 (2022/11/03): Going Deeper data wrangling lessons, part 1

| Videos to watch                                        | Project Assignment                                                   | Live Session                                                                                      |
|:-------------------------------------------------------|:---------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------|
| Complete "Going Deeper data wrangling lessons, part 1" | \- Create a function that can help you do your work more efficiently | \- Questions about Tidy Data <br> - separate() and separate_rows() <br> **Group Work** <br> - ??? |

<hr>

### Week 08 (2022/11/10): Going Deeper data wrangling lessons, part 2

| Videos to watch                                        | Project Assignment                                          | Live Session                                                          |
|:-------------------------------------------------------|:------------------------------------------------------------|:----------------------------------------------------------------------|
| Complete "Going Deeper data wrangling lessons, part 2" | \- **No new assignment** <br> - Official assignment amnesty | \- A Few of David's Favorite Functions <br> **Group Work** <br> - ??? |

<hr>

### Week 09 (2022/11/17): Advanced data viz, part 1

| Videos to watch                      | Project Assignment                                                                                                                                                                                                                                                                          | Live Session                                                                |
|:-------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------|
| Complete "Advanced data viz, part 1" | \- Improve your existing dataviz using these lessons <br> - Example improvements include; reordering or using color to highlight findings. <br> - You could also consider experimenting with other geoms. <br> - Book a 1:1 with Charlie [rfor.us/charliechat](https://rfor.us/charliechat) | \- Example functions from you <br> - Examples of High-Quality Data Viz <br> |

<hr>

### Week 10 (2022/12/01): Official Assignment Amnesty!

> This is the official assignment amnesty! This week there's no live session and we're encouraging you to jump back into the assignments at a place that makes sense for you.

<hr>

### Week 11 (2022/12/08): Advanced data viz, part 2

| Videos to watch                      | Project Assignment                                                                                                                                    | Live Session                                                           |
|:-------------------------------------|:------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------|
| Complete "Advanced data viz, part 2" | \- Switch your report to some other format (slides, dashboard, etc) <br> - Book a 1:1 with Charlie [rfor.us/charliechat](https://rfor.us/charliechat) | \- Four Tips / Example dataviz from you <br> **Group Work** <br> - ??? |

<hr>

### Week 12 (2022/12/15): Advanced RMarkdown

| Videos to watch               | Project Assignment                                                                                    | Live Session                   |
|:------------------------------|:------------------------------------------------------------------------------------------------------|:-------------------------------|
| Complete "Advanced RMarkdown" | \- Use [loom.com](loom.com) to record a video about something you can do thanks to R in 3 Months <br> | \- What else can RMarkdown do? |

<hr>

### Week 13 (2022/12/22): Wrap-up

| Videos to watch  | Project Assignment                                                                                                                                                                 | Live Session                                                                       |
|:-----------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------|
| You're finished! | \- Use [loom.com](loom.com) to record a video about something you can do thanks to R in 3 Months <br> - Book a 1:1 with Charlie [rfor.us/charliechat](https://rfor.us/charliechat) | \- Where to ask questions <br> - How to ask good questions <br> - Where to go next |
